### ISSUE TITLE
It dosen't work

### ISSUE THREAD

**Issue by VTOMV** [shashankgaurav17/vue-json-to-table-parser#1]
When i use this plugin, it donsen't work. The follow is my code.Can you help me?

`<template>
  <div>
    <JsonToTable :data="data"></JsonToTable>
  </div>
</template>
<script>
import JsonToTable from "json-to-table";
export default {
  components: {
    JsonToTable
  },
  data() {
    return {
      data: {
        name: "Rick Sanchez",
        age: 70,
        cars: ["Ford", "BMW", "Fiat"],
        family_member: {
          daughter: "Beth",
          son_in_law: "Jerry Smith",
          grand_son: "Morty",
          grand_daughter: "Summer"
        },
        awards_list: [
          {
            year: "2014",
            name: "BTVA Voice Acting Awards"
          },
          {
            year: "2015",
            name: "IGN Awards"
          },
          {
            year: "2017",
            name: "Golden Reel Awards"
          },
          "OSCAR",
          {
            test: [
              {
                nominee: "Rick and Morty",
                result: "WON"
              },
              {
                nominee: "The Ricklantis Mixup",
                result: "LOST"
              },
              {
                nominee: "Justin Roiland",
                result: "WON"
              }
            ]
          }
        ]
      },
      output: ""
    };
  }
};
</script>
<style>
table {
  border: 1px solid black;
}
tr {
  border: 1px solid black;
}
</style>`

**Comment by shashankgaurav17** [comment]
Hi @VTOMV , As of now you can copy Table2.vue file (src/components) and use it like how it is being used in App.vue. You dont need to install the package.
I will upgrade the package and fix the issue.

**Comment by shashankgaurav17** [comment]
I have fixed and updated the package and I'm closing this issue. Let me know if you face any issues.
