### ISSUE TITLE
how can i add link with @click 

### ISSUE THREAD

**Issue by RezaErfani67** [shashankgaurav17/vue-json-to-table-parser#2]
hi
i want that user click on link in table and file should be download.
how can i achieve?

**Comment by shashankgaurav17** [comment]
Hi @RezaErfani67 , Can you pls share your json.

**Comment by RezaErfani67** [comment]
oh i copy the component and customize it...
thank you

**Comment by shashankgaurav17** [comment]
ok..sounds good.
@RezaErfani67 Just for enhancing the package features, can you please explain what were your requirements and your payload.
Thanks
